In [4]:
import pandas as pd
import requests

In [24]:
df = pd.read_csv("AnalysisJob.csv", usecols=["accession", "pipeline_version"])
df = df[df["pipeline_version"] == 4.1]
accession = df["accession"].dropna().unique().tolist()

In [26]:
BASE = "https://www.ebi.ac.uk/metagenomics/api/v1/analyses"

def fetch_taxonomy(accession, as_csv=False, BASE=BASE):
    """
    Fetch taxonomic abundance for a given analysis accession.
    If as_csv=True, return a pandas DataFrame from the CSV endpoint.
    Otherwise, return the raw JSON.
    """
    # Read the ssu taxonomy CSV directly
    url = f"{BASE}/{accession}/taxonomy/ssu.csv"
    df_ssu = pd.read_csv(url)
    return df_ssu

In [27]:
all_dfs = []  # to combine across accessions

for acc in accession:
    print(f"Fetching {acc} …")
    try:
        # Option A: CSV
        df_tax = fetch_taxonomy(acc, as_csv=True)
        
        # Option B: JSON
        # json_res = fetch_taxonomy(acc, as_csv=False)
        # df_tax = parse_taxonomy_json(json_res)
        
        df_tax["accession"] = acc
        all_dfs.append(df_tax)
    except Exception as e:
        print(f"  → failed: {e}")

# Combine
master_taxonomy = pd.concat(all_dfs, ignore_index=True)

Fetching MGYA00216443 …
Fetching MGYA00216444 …
Fetching MGYA00216445 …
Fetching MGYA00216446 …
Fetching MGYA00216447 …
Fetching MGYA00216448 …
Fetching MGYA00216449 …
Fetching MGYA00216450 …
Fetching MGYA00216451 …
Fetching MGYA00216452 …
Fetching MGYA00216453 …
Fetching MGYA00216454 …
Fetching MGYA00216455 …
Fetching MGYA00216456 …
Fetching MGYA00216457 …
Fetching MGYA00216458 …
Fetching MGYA00216459 …
Fetching MGYA00216460 …
Fetching MGYA00216461 …
Fetching MGYA00216462 …
Fetching MGYA00216463 …
Fetching MGYA00216464 …
Fetching MGYA00216465 …
Fetching MGYA00216466 …
Fetching MGYA00216467 …
Fetching MGYA00216468 …
Fetching MGYA00216469 …
Fetching MGYA00216470 …
Fetching MGYA00216471 …
Fetching MGYA00216472 …
Fetching MGYA00216473 …
Fetching MGYA00216474 …
Fetching MGYA00216475 …
  → failed: HTTP Error 413: Request Entity Too Large
Fetching MGYA00216476 …
Fetching MGYA00216477 …
Fetching MGYA00216478 …
Fetching MGYA00216479 …
Fetching MGYA00216480 …
Fetching MGYA00216481 …
Fetching MGYA00216482 …
Fetching MGYA00216483 …
Fetching MGYA00216484 …
Fetching MGYA00216485 …
  → failed: HTTP Error 413: Request Entity Too Large
Fetching MGYA00216486 …
Fetching MGYA00216487 …
Fetching MGYA00216488 …
Fetching MGYA00216489 …
Fetching MGYA00216490 …
Fetching MGYA00216491 …
Fetching MGYA00216492 …
Fetching MGYA00216493 …
Fetching MGYA00216494 …
Fetching MGYA00216495 …
Fetching MGYA00216496 …
Fetching MGYA00216497 …
Fetching MGYA00216498 …
Fetching MGYA00216499 …
Fetching MGYA00216500 …
Fetching MGYA00216501 …
Fetching MGYA00216502 …
Fetching MGYA00216503 …
Fetching MGYA00216504 …
Fetching MGYA00216505 …
Fetching MGYA00216506 …
Fetching MGYA00216507 …
Fetching MGYA00216508 …
Fetching MGYA00216509 …
Fetching MGYA00216510 …
Fetching MGYA00216511 …
Fetching MGYA00216512 …
Fetching MGYA00216513 …
Fetching MGYA00216514 …
Fetching MGYA00216515 …
  → failed: No columns to parse from file
Fetching MGYA00216516 …
Fetching MGYA00216517 …
Fetching MGYA00216518 …
Fetching MGYA00216519 …
Fetching MGYA00216520 …
Fetching MGYA00216521 …
Fetching MGYA00216522 …
Fetching MGYA00216523 …
Fetching MGYA00216524 …
Fetching MGYA00216525 …
Fetching MGYA00216526 …
Fetching MGYA00216527 …
Fetching MGYA00216528 …
Fetching MGYA00216529 …
Fetching MGYA00216530 …
Fetching MGYA00216531 …
Fetching MGYA00216532 …
Fetching MGYA00216533 …
Fetching MGYA00216534 …
Fetching MGYA00216535 …
Fetching MGYA00216536 …
Fetching MGYA00216537 …
Fetching MGYA00216538 …
Fetching MGYA00216539 …
Fetching MGYA00216540 …
Fetching MGYA00216541 …
Fetching MGYA00216542 …
Fetching MGYA00216543 …
  → failed: No columns to parse from file
Fetching MGYA00216544 …
Fetching MGYA00216545 …
Fetching MGYA00216546 …
Fetching MGYA00216547 …
Fetching MGYA00216548 …
Fetching MGYA00216549 …
Fetching MGYA00216550 …
Fetching MGYA00216551 …
Fetching MGYA00216552 …
Fetching MGYA00216553 …
Fetching MGYA00216554 …
Fetching MGYA00216555 …
Fetching MGYA00216556 …
Fetching MGYA00216557 …
Fetching MGYA00216558 …
Fetching MGYA00216559 …
Fetching MGYA00216560 …
Fetching MGYA00216561 …
Fetching MGYA00216562 …
Fetching MGYA00216563 …
Fetching MGYA00216564 …
Fetching MGYA00216565 …
Fetching MGYA00216566 …
Fetching MGYA00216567 …
Fetching MGYA00216568 …
Fetching MGYA00216569 …
Fetching MGYA00216570 …
Fetching MGYA00216571 …
Fetching MGYA00216572 …
Fetching MGYA00216573 …
Fetching MGYA00216574 …
Fetching MGYA00216575 …
Fetching MGYA00216576 …
Fetching MGYA00216577 …
Fetching MGYA00216578 …
Fetching MGYA00216579 …
Fetching MGYA00216580 …
Fetching MGYA00216581 …
Fetching MGYA00216582 …
Fetching MGYA00216583 …
Fetching MGYA00216584 …
Fetching MGYA00216585 …
Fetching MGYA00216586 …
Fetching MGYA00216587 …
Fetching MGYA00216588 …
Fetching MGYA00216589 …
Fetching MGYA00216590 …
Fetching MGYA00216591 …
Fetching MGYA00216592 …
Fetching MGYA00216593 …
Fetching MGYA00216594 …
Fetching MGYA00216595 …
Fetching MGYA00216596 …
Fetching MGYA00216597 …
Fetching MGYA00216598 …
Fetching MGYA00216599 …
Fetching MGYA00216600 …
Fetching MGYA00216601 …
Fetching MGYA00216602 …
Fetching MGYA00216603 …
Fetching MGYA00216604 …
Fetching MGYA00216605 …
Fetching MGYA00216606 …
Fetching MGYA00216607 …
Fetching MGYA00216608 …
Fetching MGYA00216609 …
Fetching MGYA00216610 …
Fetching MGYA00216611 …
Fetching MGYA00216612 …
Fetching MGYA00216613 …
Fetching MGYA00216614 …
Fetching MGYA00216615 …
Fetching MGYA00216616 …
Fetching MGYA00216617 …
Fetching MGYA00216618 …
Fetching MGYA00216619 …
Fetching MGYA00216620 …
Fetching MGYA00216621 …
Fetching MGYA00216622 …
Fetching MGYA00216623 …
Fetching MGYA00216624 …
Fetching MGYA00216625 …
Fetching MGYA00216626 …
Fetching MGYA00216627 …
Fetching MGYA00216628 …
Fetching MGYA00216629 …
Fetching MGYA00216630 …
Fetching MGYA00216631 …
Fetching MGYA00216632 …
Fetching MGYA00216633 …
Fetching MGYA00216634 …
Fetching MGYA00216635 …
Fetching MGYA00216636 …
Fetching MGYA00216637 …
Fetching MGYA00216638 …
Fetching MGYA00216639 …
Fetching MGYA00216640 …
Fetching MGYA00216641 …
Fetching MGYA00216642 …
Fetching MGYA00216643 …
Fetching MGYA00216644 …
Fetching MGYA00216645 …
Fetching MGYA00216646 …
Fetching MGYA00216647 …
Fetching MGYA00216648 …
Fetching MGYA00216649 …
Fetching MGYA00216650 …
Fetching MGYA00216651 …
Fetching MGYA00216652 …
Fetching MGYA00216653 …
Fetching MGYA00216654 …
Fetching MGYA00216655 …
Fetching MGYA00216656 …
Fetching MGYA00216657 …
Fetching MGYA00216658 …
Fetching MGYA00216659 …
Fetching MGYA00216660 …
Fetching MGYA00216661 …
Fetching MGYA00216662 …
Fetching MGYA00216663 …
Fetching MGYA00216664 …
Fetching MGYA00216665 …
Fetching MGYA00216666 …
Fetching MGYA00216667 …
Fetching MGYA00216668 …
Fetching MGYA00216669 …
Fetching MGYA00216670 …
Fetching MGYA00216671 …
Fetching MGYA00216672 …
Fetching MGYA00216673 …
Fetching MGYA00216674 …
Fetching MGYA00216675 …
Fetching MGYA00216676 …

In [54]:
master_taxonomy.dropna(subset=["hierarchy.phylum"])

,count,domain,hierarchy.class,hierarchy.family,hierarchy.genus,hierarchy.kingdom,hierarchy.order,hierarchy.phylum,hierarchy.species,hierarchy.super kingdom,lineage,name,parent,pipeline_version,rank,url,accession
1,1,Archaea,NaN,NaN,NaN,NaN,NaN,Euryarchaeota,NaN,Archaea,Archaea::Euryarchaeota,Euryarchaeota,NaN,4.1,phylum,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216443
2,3,Archaea,Methanobacteria,NaN,NaN,NaN,Methanobacteriales,Euryarchaeota,NaN,Archaea,Archaea::Euryarchaeota:Methanobacteria:Methano...,Methanobacteriales,Methanobacteria,4.1,order,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216443
3,105,Archaea,Methanobacteria,Methanobacteriaceae,NaN,NaN,Methanobacteriales,Euryarchaeota,NaN,Archaea,Archaea::Euryarchaeota:Methanobacteria:Methano...,Methanobacteriaceae,Methanobacteriales,4.1,family,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216443
4,9,Archaea,Methanobacteria,Methanobacteriaceae,Methanobacterium,NaN,Methanobacteriales,Euryarchaeota,NaN,Archaea,Archaea::Euryarchaeota:Methanobacteria:Methano...,Methanobacterium,Methanobacteriaceae,4.1,genus,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216443
5,246,Archaea,Methanobacteria,Methanobacteriaceae,Methanobrevibacter,NaN,Methanobacteriales,Euryarchaeota,NaN,Archaea,Archaea::Euryarchaeota:Methanobacteria:Methano...,Methanobrevibacter,Methanobacteriaceae,4.1,genus,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147544,1,Eukaryota,Chromadorea,Diploscapteridae,NaN,Metazoa,Rhabditida,Nematoda,NaN,Eukaryota,Eukaryota:Metazoa:Nematoda:Chromadorea:Rhabdit...,Diploscapteridae,Rhabditida,4.1,family,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216676
147545,1,Eukaryota,Bdelloidea,NaN,NaN,Metazoa,NaN,Rotifera,NaN,Eukaryota,Eukaryota:Metazoa:Rotifera:Bdelloidea,Bdelloidea,Rotifera,4.1,class,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216676
147546,1,Eukaryota,Bdelloidea,Adinetidae,Adineta,Metazoa,Adinetida,Rotifera,Adineta_vaga,Eukaryota,Eukaryota:Metazoa:Rotifera:Bdelloidea:Adinetid...,Adineta_vaga,Adineta,4.1,species,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216676
147548,3,Eukaryota,NaN,NaN,NaN,Viridiplantae,NaN,Chlorophyta,NaN,Eukaryota,Eukaryota:Viridiplantae:Chlorophyta,Chlorophyta,Viridiplantae,4.1,phylum,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216676
147549,2,Eukaryota,NaN,Fabaceae,NaN,Viridiplantae,Fabales,Streptophyta,NaN,Eukaryota,Eukaryota:Viridiplantae:Streptophyta::Fabales:...,Fabaceae,Fabales,4.1,family,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00216676

In [69]:
selected_tax_4_1 = master_taxonomy[["count", "domain", "hierarchy.phylum", "accession"]].dropna(subset=["hierarchy.phylum"])

selected_tax_4_1["phylum_level"] = selected_tax_4_1["domain"].astype(str) + " " + selected_tax_4_1["hierarchy.phylum"].astype(str)

selected_tax_4_1 = selected_tax_4_1[["count", "phylum_level", "accession"]]

selected_tax_4_1

# pivot to wide format
df_wide_4_1 = selected_tax_4_1.pivot_table(
    index='accession',
    columns='phylum_level',
    values='count',
    aggfunc='sum',
    fill_value=0        # fill missing combinations with zero
)

# (optional) if you want the lineage levels back as normal columns rather than a MultiIndex:
df_wide_4_1 = df_wide_4_1.reset_index().rename_axis(columns=None)

df_wide_4_1["pipeline"] = "4.1"

# Reorder

cols = df_wide_4_1.columns.tolist()
# build a new order: your column first, then all others in original order
new_order = [cols[0]] + ['pipeline'] + [c for c in cols if c not in (cols[0], 'pipeline')]

# reindex df
df_wide_4_1 = df_wide_4_1[new_order]

df_wide_4_1

,accession,pipeline,Archaea Candidatus_Diapherotrites,Archaea Candidatus_Micrarchaeota,Archaea Candidatus_Nanohaloarchaeota,Archaea Candidatus_Verstraetearchaeota,Archaea Crenarchaeota,Archaea Euryarchaeota,Archaea Nanoarchaeota,Archaea Thaumarchaeota,...,Eukaryota Nematoda,Eukaryota Phaeophyceae,Eukaryota Picozoa,Eukaryota Platyhelminthes,Eukaryota Porifera,Eukaryota Rotifera,Eukaryota Streptophyta,Eukaryota Tardigrada,Eukaryota Xenacoelomorpha,Eukaryota Zoopagomycota
0,MGYA00216443,4.1,0,0,0,0,0,926,0,0,...,204,1,0,0,0,10,43,2,0,0
1,MGYA00216444,4.1,0,0,0,0,4,338,0,4,...,26,0,0,10,0,2,18,0,0,1
2,MGYA00216445,4.1,0,0,0,0,0,104,0,0,...,33,1,0,0,0,4,25,0,0,0
3,MGYA00216446,4.1,0,0,0,0,0,423,0,13,...,39,1,0,25,0,1,12,0,0,1
4,MGYA00216447,4.1,1,0,0,0,1,159,0,0,...,165,0,0,0,0,1,10,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,MGYA00216672,4.1,0,0,0,0,0,10,0,0,...,15,0,0,0,0,1,2,0,0,0
226,MGYA00216673,4.1,0,0,0,0,0,147,0,0,...,19,0,0,0,0,1,1,0,0,0
227,MGYA00216674,4.1,3,0,0,0,0,19,0,0,...,25,0,0,0,0,9,0,0,0,0
228,MGYA00216675,4.1,0,0,0,0,0,114,0,0,...,4,0,0,0,0,1,3,0,0,0
229,MGYA00216676,4.1,0,0,0,0,0,47,0,0,...,6,0,0,0,0,2,2,0,0,0

In [71]:
df = pd.read_csv("AnalysisJob.csv", usecols=["accession", "pipeline_version"])
df = df[df["pipeline_version"] == 3.0]
accession = df["accession"].dropna().unique().tolist()

In [70]:
def fetch_taxonomy_alt(accession, as_csv=False, BASE=BASE):
    """
    Fetch taxonomic abundance for a given analysis accession.
    If as_csv=True, return a pandas DataFrame from the CSV endpoint.
    Otherwise, return the raw JSON.
    """
    # Read the ssu taxonomy CSV directly
    url = f"{BASE}/{accession}/taxonomy.csv"
    df_ssu = pd.read_csv(url)
    return df_ssu

In [72]:
all_dfs = []  # to combine across accessions

for acc in accession:
    print(f"Fetching {acc} …")
    try:
        # Option A: CSV
        df_tax = fetch_taxonomy_alt(acc, as_csv=True)
        
        # Option B: JSON
        # json_res = fetch_taxonomy(acc, as_csv=False)
        # df_tax = parse_taxonomy_json(json_res)
        
        df_tax["accession"] = acc
        all_dfs.append(df_tax)
    except Exception as e:
        print(f"  → failed: {e}")

# Combine
master_taxonomy = pd.concat(all_dfs, ignore_index=True)

Fetching MGYA00085622 …
Fetching MGYA00085623 …
Fetching MGYA00085624 …
Fetching MGYA00085625 …
Fetching MGYA00085626 …
Fetching MGYA00085627 …
Fetching MGYA00085628 …
Fetching MGYA00085629 …
Fetching MGYA00085630 …
Fetching MGYA00085631 …
Fetching MGYA00085632 …
Fetching MGYA00085633 …
Fetching MGYA00085634 …
Fetching MGYA00085635 …
Fetching MGYA00085636 …
Fetching MGYA00085637 …
Fetching MGYA00085638 …
Fetching MGYA00085639 …
Fetching MGYA00085640 …
Fetching MGYA00085641 …
Fetching MGYA00085642 …
Fetching MGYA00085643 …
Fetching MGYA00085644 …
Fetching MGYA00085645 …
Fetching MGYA00085646 …
Fetching MGYA00085647 …
Fetching MGYA00085648 …
Fetching MGYA00085649 …
Fetching MGYA00085650 …
Fetching MGYA00085651 …
Fetching MGYA00085652 …
Fetching MGYA00085653 …
Fetching MGYA00085654 …
Fetching MGYA00085655 …
Fetching MGYA00085656 …
Fetching MGYA00085657 …
Fetching MGYA00085658 …
Fetching MGYA00085659 …
Fetching MGYA00085660 …
Fetching MGYA00085661 …
Fetching MGYA00085662 …
Fetching MGYA00085663 …
Fetching MGYA00085664 …
Fetching MGYA00085665 …
Fetching MGYA00085666 …
Fetching MGYA00085667 …
Fetching MGYA00085668 …
Fetching MGYA00085669 …
Fetching MGYA00085670 …
Fetching MGYA00085671 …
Fetching MGYA00085672 …
Fetching MGYA00085673 …
Fetching MGYA00085674 …
Fetching MGYA00085675 …
Fetching MGYA00085676 …
Fetching MGYA00085677 …
Fetching MGYA00085678 …
Fetching MGYA00085679 …
Fetching MGYA00085680 …
Fetching MGYA00085681 …
Fetching MGYA00085682 …
Fetching MGYA00085683 …
Fetching MGYA00085684 …
Fetching MGYA00085685 …
Fetching MGYA00085686 …
Fetching MGYA00085687 …
Fetching MGYA00085688 …
Fetching MGYA00085689 …
Fetching MGYA00085690 …
Fetching MGYA00085691 …
Fetching MGYA00085692 …
Fetching MGYA00085693 …
Fetching MGYA00085694 …
Fetching MGYA00085695 …
Fetching MGYA00085696 …
Fetching MGYA00085697 …
Fetching MGYA00085698 …
Fetching MGYA00085699 …
Fetching MGYA00085700 …
Fetching MGYA00085701 …
Fetching MGYA00085702 …
Fetching MGYA00085703 …
Fetching MGYA00085704 …
Fetching MGYA00085705 …
Fetching MGYA00085706 …
Fetching MGYA00085707 …
Fetching MGYA00085708 …
Fetching MGYA00085709 …
Fetching MGYA00085710 …
Fetching MGYA00085711 …
Fetching MGYA00085712 …
Fetching MGYA00085713 …
Fetching MGYA00085714 …
Fetching MGYA00085715 …
Fetching MGYA00085716 …
Fetching MGYA00085717 …
Fetching MGYA00085718 …
Fetching MGYA00085719 …
Fetching MGYA00085720 …
Fetching MGYA00085721 …
Fetching MGYA00085722 …
Fetching MGYA00085723 …
Fetching MGYA00085724 …
Fetching MGYA00085725 …
Fetching MGYA00085726 …
Fetching MGYA00085727 …
Fetching MGYA00085728 …
Fetching MGYA00085729 …
Fetching MGYA00085730 …
Fetching MGYA00085731 …
Fetching MGYA00085732 …
Fetching MGYA00085733 …
Fetching MGYA00085734 …
Fetching MGYA00085735 …
Fetching MGYA00085736 …
Fetching MGYA00085737 …
Fetching MGYA00085738 …
Fetching MGYA00085739 …
Fetching MGYA00085740 …
Fetching MGYA00085741 …
Fetching MGYA00085742 …
Fetching MGYA00085743 …
Fetching MGYA00085744 …
Fetching MGYA00085745 …
Fetching MGYA00085746 …
Fetching MGYA00085747 …
Fetching MGYA00085748 …
Fetching MGYA00085749 …
Fetching MGYA00085750 …
Fetching MGYA00085751 …
Fetching MGYA00085752 …
Fetching MGYA00085753 …
Fetching MGYA00085754 …
Fetching MGYA00085755 …
Fetching MGYA00085756 …
Fetching MGYA00085757 …
Fetching MGYA00085758 …
Fetching MGYA00085759 …
Fetching MGYA00085760 …
Fetching MGYA00085761 …
Fetching MGYA00085762 …
Fetching MGYA00085763 …
Fetching MGYA00085764 …
Fetching MGYA00085765 …
Fetching MGYA00085766 …
Fetching MGYA00085767 …
Fetching MGYA00085768 …
Fetching MGYA00085769 …
Fetching MGYA00085770 …
Fetching MGYA00085771 …
Fetching MGYA00085772 …
Fetching MGYA00085773 …
Fetching MGYA00085774 …
Fetching MGYA00085775 …
Fetching MGYA00085776 …
Fetching MGYA00085777 …
Fetching MGYA00085778 …
Fetching MGYA00085779 …
Fetching MGYA00085780 …
Fetching MGYA00085781 …
Fetching MGYA00085782 …
Fetching MGYA00085783 …
Fetching MGYA00085784 …
Fetching MGYA00085785 …
Fetching MGYA00085786 …
Fetching MGYA00085787 …
Fetching MGYA00085788 …
Fetching MGYA00085789 …
Fetching MGYA00085790 …
Fetching MGYA00085791 …
Fetching MGYA00085792 …
Fetching MGYA00085793 …
Fetching MGYA00085794 …
Fetching MGYA00085795 …
Fetching MGYA00085796 …
Fetching MGYA00085797 …
Fetching MGYA00085798 …
Fetching MGYA00085799 …
Fetching MGYA00085800 …

In [ ]:
master_taxonomy

,count,domain,hierarchy.class,hierarchy.family,hierarchy.genus,hierarchy.kingdom,hierarchy.order,hierarchy.phylum,hierarchy.species,lineage,name,parent,pipeline_version,rank,url,accession
0,5,Bacteria,Synergistia,Dethiosulfovibrionaceae,PD-UASB-13,Bacteria,Synergistales,Synergistetes,NaN,Bacteria:Synergistetes:Synergistia:Synergistal...,PD-UASB-13,Dethiosulfovibrionaceae,3.0,genus,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085622
1,20,Bacteria,Betaproteobacteria,NaN,NaN,Bacteria,MND1,Proteobacteria,NaN,Bacteria:Proteobacteria:Betaproteobacteria:MND1,MND1,Betaproteobacteria,3.0,order,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085622
2,1,Bacteria,Alphaproteobacteria,Rhodobacteraceae,Amaricoccus,Bacteria,Rhodobacterales,Proteobacteria,NaN,Bacteria:Proteobacteria:Alphaproteobacteria:Rh...,Amaricoccus,Rhodobacteraceae,3.0,genus,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085622
3,8,Bacteria,Bacteroidia,S24-7,NaN,Bacteria,Bacteroidales,Bacteroidetes,NaN,Bacteria:Bacteroidetes:Bacteroidia:Bacteroidal...,S24-7,Bacteroidales,3.0,family,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085622
4,23,Bacteria,Alphaproteobacteria,Rhizobiaceae,NaN,Bacteria,Rhizobiales,Proteobacteria,NaN,Bacteria:Proteobacteria:Alphaproteobacteria:Rh...,Rhizobiaceae,Rhizobiales,3.0,family,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130228,1,Bacteria,Clostridia,Clostridiaceae,Clostridium,Bacteria,Clostridiales,Firmicutes,tetani,Bacteria:Firmicutes:Clostridia:Clostridiales:C...,tetani,Clostridium,3.0,species,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085800
130229,9,Bacteria,Gammaproteobacteria,Oceanospirillaceae,NaN,Bacteria,Oceanospirillales,Proteobacteria,NaN,Bacteria:Proteobacteria:Gammaproteobacteria:Oc...,Oceanospirillaceae,Oceanospirillales,3.0,family,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085800
130230,4,Bacteria,Alphaproteobacteria,Sphingomonadaceae,Sphingobium,Bacteria,Sphingomonadales,Proteobacteria,NaN,Bacteria:Proteobacteria:Alphaproteobacteria:Sp...,Sphingobium,Sphingomonadaceae,3.0,genus,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085800
130231,12,Bacteria,Betaproteobacteria,Comamonadaceae,Variovorax,Bacteria,Burkholderiales,Proteobacteria,NaN,Bacteria:Proteobacteria:Betaproteobacteria:Bur...,Variovorax,Comamonadaceae,3.0,genus,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085800
130232,6,Bacteria,Gammaproteobacteria,Marinicellaceae,NaN,Bacteria,Marinicellales,Proteobacteria,NaN,Bacteria:Proteobacteria:Gammaproteobacteria:Ma...,Marinicellaceae,Marinicellales,3.0,family,https://www.ebi.ac.uk/metagenomics/api/v1/anno...,MGYA00085800

In [76]:
selected_tax_3_0 = master_taxonomy[["count", "domain", "hierarchy.phylum", "accession"]].dropna(subset=["hierarchy.phylum"])

selected_tax_3_0["phylum_level"] = selected_tax_3_0["domain"].astype(str) + " " + selected_tax_3_0["hierarchy.phylum"].astype(str)

selected_tax_3_0 = selected_tax_3_0[["count", "phylum_level", "accession"]]

selected_tax_3_0

# pivot to wide format
df_wide_3_0 = selected_tax_3_0.pivot_table(
    index='accession',
    columns='phylum_level',
    values='count',
    aggfunc='sum',
    fill_value=0        # fill missing combinations with zero
)

# (optional) if you want the lineage levels back as normal columns rather than a MultiIndex:
df_wide_3_0 = df_wide_3_0.reset_index().rename_axis(columns=None)

df_wide_3_0["pipeline"] = "3.0"

# Reorder

cols = df_wide_3_0.columns.tolist()
# build a new order: your column first, then all others in original order
new_order = [cols[0]] + ['pipeline'] + [c for c in cols if c not in (cols[0], 'pipeline')]

# reindex df
df_wide_3_0 = df_wide_3_0[new_order]

df_wide_3_0

,accession,pipeline,Archaea Crenarchaeota,Archaea Euryarchaeota,Archaea Parvarchaeota,Bacteria AC1,Bacteria Acidobacteria,Bacteria Actinobacteria,Bacteria Aquificae,Bacteria Armatimonadetes,...,Bacteria Verrucomicrobia,Bacteria WPS-2,Bacteria WS1,Bacteria WS2,Bacteria WS3,Bacteria WS4,Bacteria WS5,Bacteria WS6,Bacteria WWE1,Bacteria ZB3
0,MGYA00085622,3.0,0,95,0,0,4,1236,0,1,...,169,4,0,1,0,0,0,0,0,0
1,MGYA00085623,3.0,0,69,0,0,24,1046,0,4,...,222,10,0,0,1,0,0,2,3,0
2,MGYA00085624,3.0,0,16,0,0,29,403,0,3,...,74,12,0,0,0,0,0,0,0,0
3,MGYA00085625,3.0,0,26,0,0,4,377,0,5,...,384,3,3,0,0,0,0,6,18,0
4,MGYA00085626,3.0,0,10,0,0,3,88,0,0,...,13,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,MGYA00085796,3.0,0,209,0,0,32,3202,0,9,...,817,11,0,0,1,1,0,24,1,0
175,MGYA00085797,3.0,0,78,0,0,1,323,0,2,...,98,2,0,0,1,0,0,8,2,0
176,MGYA00085798,3.0,0,33,0,0,3,478,0,2,...,55,3,0,0,1,0,0,3,2,0
177,MGYA00085799,3.0,7,323,0,0,306,1016,0,13,...,726,12,2,0,10,0,0,244,16,1
178,MGYA00085800,3.0,0,31,0,0,8,320,0,1,...,96,1,0,0,0,1,0,0,0,0

In [78]:
concat_pd = pd.concat([df_wide_4_1, df_wide_3_0], axis=0, ignore_index=True, sort=False).fillna(0)

concat_pd

,accession,pipeline,Archaea Candidatus_Diapherotrites,Archaea Candidatus_Micrarchaeota,Archaea Candidatus_Nanohaloarchaeota,Archaea Candidatus_Verstraetearchaeota,Archaea Crenarchaeota,Archaea Euryarchaeota,Archaea Nanoarchaeota,Archaea Thaumarchaeota,...,Bacteria Thermi,Bacteria WPS-2,Bacteria WS1,Bacteria WS2,Bacteria WS3,Bacteria WS4,Bacteria WS5,Bacteria WS6,Bacteria WWE1,Bacteria ZB3
0,MGYA00216443,4.1,0.0,0.0,0.0,0.0,0,926,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,MGYA00216444,4.1,0.0,0.0,0.0,0.0,4,338,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,MGYA00216445,4.1,0.0,0.0,0.0,0.0,0,104,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,MGYA00216446,4.1,0.0,0.0,0.0,0.0,0,423,0.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,MGYA00216447,4.1,1.0,0.0,0.0,0.0,1,159,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404,MGYA00085796,3.0,0.0,0.0,0.0,0.0,0,209,0.0,0.0,...,3.0,11.0,0.0,0.0,1.0,1.0,0.0,24.0,1.0,0.0
405,MGYA00085797,3.0,0.0,0.0,0.0,0.0,0,78,0.0,0.0,...,0.0,2.0,0.0,0.0,1.0,0.0,0.0,8.0,2.0,0.0
406,MGYA00085798,3.0,0.0,0.0,0.0,0.0,0,33,0.0,0.0,...,0.0,3.0,0.0,0.0,1.0,0.0,0.0,3.0,2.0,0.0
407,MGYA00085799,3.0,0.0,0.0,0.0,0.0,7,323,0.0,0.0,...,0.0,12.0,2.0,0.0,10.0,0.0,0.0,244.0,16.0,1.0
408,MGYA00085800,3.0,0.0,0.0,0.0,0.0,0,31,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [80]:
df = pd.read_csv("AnalysisJob.csv", usecols=["accession"])
accession = df["accession"].dropna().unique().tolist()

In [88]:
BASE = "https://www.ebi.ac.uk/metagenomics/api/v1"

def get_run_id_for_analysis(accession):
    """Return the MGnify sample ID (e.g. ERS…) for a given analysis accession."""
    url = f"{BASE}/analyses/{accession}"
    resp = requests.get(url)
    resp.raise_for_status()
    data = resp.json()
    # Navigate into the JSON: relationships → sample → data → id
    return data["data"]["relationships"]["run"]["data"]["id"]

def get_country_for_sample(sample_id):
    """
    Fetch the sample record and return its 'country' attribute.
    """
    url = f"{BASE}/samples/{sample_id}"
    resp = requests.get(url)
    resp.raise_for_status()
    attrs = resp.json()["data"]["attributes"]
    # the exact key used by the API:
    return attrs.get("geographic location (country and/or sea,region)")

In [89]:
# 2) Fetch country for each
records = []
for acc in accession:
    try:
        samp_id = get_run_id_for_analysis(acc)
        records.append({"accession": acc, "sample_id": samp_id})
        print(f"Sample ID for {acc}: {samp_id}")
    except Exception as e:
        # you can choose to log or skip
        records.append({"accession": acc, "sample_id": None})
        print(f"Warning fetching {acc}: {e}")

# 3) Build and save
df_samples = pd.DataFrame(records)

df_samples

Sample ID for MGYA00216443: ERR1713390
Sample ID for MGYA00216444: ERR1713337
Sample ID for MGYA00216445: ERR1726005
Sample ID for MGYA00216446: ERR1725950
Sample ID for MGYA00216447: ERR1725956
Sample ID for MGYA00216448: ERR1725963
Sample ID for MGYA00216449: ERR1713357
Sample ID for MGYA00216450: ERR1713382
Sample ID for MGYA00216451: ERR1725952
Sample ID for MGYA00216452: ERR1725987
Sample ID for MGYA00216453: ERR1713402
Sample ID for MGYA00216454: ERR1725949
Sample ID for MGYA00216455: ERR1725984
Sample ID for MGYA00216456: ERR2592272
Sample ID for MGYA00216457: ERR1713360
Sample ID for MGYA00216458: ERR1726002
Sample ID for MGYA00216459: ERR1725982
Sample ID for MGYA00216460: ERR2592276
Sample ID for MGYA00216461: ERR1725957
Sample ID for MGYA00216462: ERR2592250
Sample ID for MGYA00216463: ERR1713385
Sample ID for MGYA00216464: ERR2592271
Sample ID for MGYA00216465: ERR2592331
Sample ID for MGYA00216466: ERR1713381
Sample ID for MGYA00216467: ERR2592247
Sample ID for MGYA00216468: ERR1725974
Sample ID for MGYA00216469: ERR1713359
Sample ID for MGYA00216470: ERR1725961
Sample ID for MGYA00216471: ERR1726033
Sample ID for MGYA00216472: ERR1713373
Sample ID for MGYA00216473: ERR1713350
Sample ID for MGYA00216474: ERR2592259
Sample ID for MGYA00216475: ERR1713344
Sample ID for MGYA00216476: ERR1713387
Sample ID for MGYA00216477: ERR1725975
Sample ID for MGYA00216478: ERR1726010
Sample ID for MGYA00216479: ERR1726008
Sample ID for MGYA00216480: ERR1713389
Sample ID for MGYA00216481: ERR2592264
Sample ID for MGYA00216482: ERR1726018
Sample ID for MGYA00216483: ERR1725951
Sample ID for MGYA00216484: ERR1713351
Sample ID for MGYA00216485: ERR1713384
Sample ID for MGYA00216486: ERR2592280
Sample ID for MGYA00216487: ERR1713369
Sample ID for MGYA00216488: ERR1713388
Sample ID for MGYA00216489: ERR1713355
Sample ID for MGYA00216490: ERR1713352
Sample ID for MGYA00216491: ERR2592263
Sample ID for MGYA00216492: ERR1725942
Sample ID for MGYA00216493: ERR2592245
Sample ID for MGYA00216494: ERR1725992
Sample ID for MGYA00216495: ERR1725945
Sample ID for MGYA00216496: ERR1713334
Sample ID for MGYA00216497: ERR2592265
Sample ID for MGYA00216498: ERR1725964
Sample ID for MGYA00216499: ERR1726019
Sample ID for MGYA00216500: ERR1713392
Sample ID for MGYA00216501: ERR1713349
Sample ID for MGYA00216502: ERR2592262
Sample ID for MGYA00216503: ERR1713383
Sample ID for MGYA00216504: ERR1713391
Sample ID for MGYA00216505: ERR2592334
Sample ID for MGYA00216506: ERR1713406
Sample ID for MGYA00216507: ERR1713332
Sample ID for MGYA00216508: ERR1713372
Sample ID for MGYA00216509: ERR1725977
Sample ID for MGYA00216510: ERR1726014
Sample ID for MGYA00216511: ERR1713356
Sample ID for MGYA00216512: ERR1713346
Sample ID for MGYA00216513: ERR2592248
Sample ID for MGYA00216514: ERR1725998
Sample ID for MGYA00216515: ERR1725976
Sample ID for MGYA00216516: ERR2592251
Sample ID for MGYA00216517: ERR1713398
Sample ID for MGYA00216518: ERR2592340
Sample ID for MGYA00216519: ERR2592338
Sample ID for MGYA00216520: ERR2592329
Sample ID for MGYA00216521: ERR1713401
Sample ID for MGYA00216522: ERR2592256
Sample ID for MGYA00216523: ERR1713396
Sample ID for MGYA00216524: ERR1726017
Sample ID for MGYA00216525: ERR1725947
Sample ID for MGYA00216526: ERR2592266
Sample ID for MGYA00216527: ERR1725968
Sample ID for MGYA00216528: ERR1726028
Sample ID for MGYA00216529: ERR1725938
Sample ID for MGYA00216530: ERR1725943
Sample ID for MGYA00216531: ERR2592246
Sample ID for MGYA00216532: ERR1725946
Sample ID for MGYA00216533: ERR1713379
Sample ID for MGYA00216534: ERR1726027
Sample ID for MGYA00216535: ERR1726012
Sample ID for MGYA00216536: ERR1725993
Sample ID for MGYA00216537: ERR1726023
Sample ID for MGYA00216538: ERR1725960
Sample ID for MGYA00216539: ERR1726025
Sample ID for MGYA00216540: ERR1713407
Sample ID for MGYA00216541: ERR1725978
Sample ID for MGYA00216542: ERR2592277
Sample ID for MGYA00216543: ERR2592254
Sample ID for MGYA00216544: ERR1725953
Sample ID for MGYA00216545: ERR1713338
Sample ID for MGYA00216546: ERR1725948
Sample ID for MGYA00216547: ERR1725990
Sample ID for MGYA00216548: ERR1713409
Sample ID for MGYA00216549: ERR2592281
Sample ID for MGYA00216550: ERR1725958
Sample ID for MGYA00216551: ERR2592332
Sample ID for MGYA00216552: ERR1713404
Sample ID for MGYA00216553: ERR1726026
Sample ID for MGYA00216554: ERR1725997
Sample ID for MGYA00216555: ERR1726006
Sample ID for MGYA00216556: ERR1725986
Sample ID for MGYA00216557: ERR1725988
Sample ID for MGYA00216558: ERR2592261
Sample ID for MGYA00216559: ERR1725971
Sample ID for MGYA00216560: ERR1725970
Sample ID for MGYA00216561: ERR1725979
Sample ID for MGYA00216562: ERR1713377
Sample ID for MGYA00216563: ERR1713394
Sample ID for MGYA00216564: ERR1726034
Sample ID for MGYA00216565: ERR2592273
Sample ID for MGYA00216566: ERR2592258
Sample ID for MGYA00216567: ERR2592337
Sample ID for MGYA00216568: ERR1726000
Sample ID for MGYA00216569: ERR1726001
Sample ID for MGYA00216570: ERR2592336
Sample ID for MGYA00216571: ERR1713378
Sample ID for MGYA00216572: ERR1713375
Sample ID for MGYA00216573: ERR1725967
Sample ID for MGYA00216574: ERR1713366
Sample ID for MGYA00216575: ERR1713364
Sample ID for MGYA00216576: ERR1713342
Sample ID for MGYA00216577: ERR1713335
Sample ID for MGYA00216578: ERR1725985
Sample ID for MGYA00216579: ERR1713376
Sample ID for MGYA00216580: ERR1726022
Sample ID for MGYA00216581: ERR2592267
Sample ID for MGYA00216582: ERR1713340
Sample ID for MGYA00216583: ERR1725955
Sample ID for MGYA00216584: ERR1725959
Sample ID for MGYA00216585: ERR1713353
Sample ID for MGYA00216586: ERR1726011
Sample ID for MGYA00216587: ERR1713336
Sample ID for MGYA00216588: ERR1713400
Sample ID for MGYA00216589: ERR2592278
Sample ID for MGYA00216590: ERR1713374
Sample ID for MGYA00216591: ERR1725954
Sample ID for MGYA00216592: ERR1713397
Sample ID for MGYA00216593: ERR1725941
Sample ID for MGYA00216594: ERR1713341
Sample ID for MGYA00216595: ERR1713411
Sample ID for MGYA00216596: ERR1713358
Sample ID for MGYA00216597: ERR1725995
Sample ID for MGYA00216598: ERR2592269
Sample ID for MGYA00216599: ERR2592343
Sample ID for MGYA00216600: ERR2592341
Sample ID for MGYA00216601: ERR1713393
Sample ID for MGYA00216602: ERR1725981
Sample ID for MGYA00216603: ERR1726031
Sample ID for MGYA00216604: ERR1713399
Sample ID for MGYA00216605: ERR1713408
Sample ID for MGYA00216606: ERR1725980
Sample ID for MGYA00216607: ERR2592283
Sample ID for MGYA00216608: ERR2592279
Sample ID for MGYA00216609: ERR2592268
Sample ID for MGYA00216610: ERR1725972
Sample ID for MGYA00216611: ERR1725973
Sample ID for MGYA00216612: ERR1726029
Sample ID for MGYA00216613: ERR1713343
Sample ID for MGYA00216614: ERR2592282
Sample ID for MGYA00216615: ERR2592257
Sample ID for MGYA00216616: ERR1726030
Sample ID for MGYA00216617: ERR2592252
Sample ID for MGYA00216618: ERR2592274
Sample ID for MGYA00216619: ERR1713395
Sample ID for MGYA00216620: ERR2592244
Sample ID for MGYA00216621: ERR2592342
Sample ID for MGYA00216622: ERR1713380
Sample ID for MGYA00216623: ERR1725965
Sample ID for MGYA00216624: ERR1713348
Sample ID for MGYA00216625: ERR1725939
Sample ID for MGYA00216626: ERR1725996
Sample ID for MGYA00216627: ERR1713331
Sample ID for MGYA00216628: ERR2592253
Sample ID for MGYA00216629: ERR2592270
Sample ID for MGYA00216630: ERR1713405
Sample ID for MGYA00216631: ERR1713365
Sample ID for MGYA00216632: ERR1713333
Sample ID for MGYA00216633: ERR2592249
Sample ID for MGYA00216634: ERR1725966
Sample ID for MGYA00216635: ERR1713345
Sample ID for MGYA00216636: ERR1726009
Sample ID for MGYA00216637: ERR1713361
Sample ID for MGYA00216638: ERR1726024
Sample ID for MGYA00216639: ERR1725991
Sample ID for MGYA00216640: ERR2592339
Sample ID for MGYA00216641: ERR1726007
Sample ID for MGYA00216642: ERR1713362
Sample ID for MGYA00216643: ERR1726021
Sample ID for MGYA00216644: ERR1713363
Sample ID for MGYA00216645: ERR1726032
Sample ID for MGYA00216646: ERR1726016
Sample ID for MGYA00216647: ERR1713370
Sample ID for MGYA00216648: ERR1713386
Sample ID for MGYA00216649: ERR1726003
Sample ID for MGYA00216650: ERR1726004
Sample ID for MGYA00216651: ERR2592255
Sample ID for MGYA00216652: ERR1725989
Sample ID for MGYA00216653: ERR1725962
Sample ID for MGYA00216654: ERR1713368
Sample ID for MGYA00216655: ERR1726015
Sample ID for MGYA00216656: ERR1713410
Sample ID for MGYA00216657: ERR1713354
Sample ID for MGYA00216658: ERR1726035
Sample ID for MGYA00216659: ERR2592333
Sample ID for MGYA00216660: ERR1725944
Sample ID for MGYA00216661: ERR2592260
Sample ID for MGYA00216662: ERR1713347
Sample ID for MGYA00216663: ERR1725994
Sample ID for MGYA00216664: ERR1726013
Sample ID for MGYA00216665: ERR1725969
Sample ID for MGYA00216666: ERR2592335
Sample ID for MGYA00216667: ERR1725999
Sample ID for MGYA00216668: ERR2592275
Sample ID for MGYA00216669: ERR1713403
Sample ID for MGYA00216670: ERR1713367
Sample ID for MGYA00216671: ERR1725940
Sample ID for MGYA00216672: ERR1713339
Sample ID for MGYA00216673: ERR1726020
Sample ID for MGYA00216674: ERR2592328
Sample ID for MGYA00216675: ERR1725983
Sample ID for MGYA00216676: ERR1713371
Sample ID for MGYA00085622: ERR1725944
Sample ID for MGYA00085623: ERR1713392
Sample ID for MGYA00085624: ERR1725946
Sample ID for MGYA00085625: ERR1713376
Sample ID for MGYA00085626: ERR1713357
Sample ID for MGYA00085627: ERR1713339
Sample ID for MGYA00085628: ERR1725994
Sample ID for MGYA00085629: ERR1713398
Sample ID for MGYA00085630: ERR1713336
Sample ID for MGYA00085631: ERR1713407
Sample ID for MGYA00085632: ERR1713360
Sample ID for MGYA00085633: ERR1725941
Sample ID for MGYA00085634: ERR1713348
Sample ID for MGYA00085635: ERR1713386
Sample ID for MGYA00085636: ERR1725998
Sample ID for MGYA00085637: ERR1726020
Sample ID for MGYA00085638: ERR1713351
Sample ID for MGYA00085639: ERR1725992
Sample ID for MGYA00085640: ERR1713333
Sample ID for MGYA00085641: ERR1726026
Sample ID for MGYA00085642: ERR1713342
Sample ID for MGYA00085643: ERR1725970
Sample ID for MGYA00085644: ERR1713389
Sample ID for MGYA00085645: ERR1713343
Sample ID for MGYA00085646: ERR1713391
Sample ID for MGYA00085647: ERR1713406
Sample ID for MGYA00085648: ERR1725986
Sample ID for MGYA00085649: ERR1713338
Sample ID for MGYA00085650: ERR1725999
Sample ID for MGYA00085651: ERR1713411
Sample ID for MGYA00085652: ERR1725987
Sample ID for MGYA00085653: ERR1713404
Sample ID for MGYA00085654: ERR1713331
Sample ID for MGYA00085655: ERR1713399
Sample ID for MGYA00085656: ERR1725938
Sample ID for MGYA00085657: ERR1725955
Sample ID for MGYA00085658: ERR1725989
Sample ID for MGYA00085659: ERR1713341
Sample ID for MGYA00085660: ERR1726005
Sample ID for MGYA00085661: ERR1726017
Sample ID for MGYA00085662: ERR1725977
Sample ID for MGYA00085663: ERR1725991
Sample ID for MGYA00085664: ERR1713337
Sample ID for MGYA00085665: ERR1713346
Sample ID for MGYA00085666: ERR1713349
Sample ID for MGYA00085667: ERR1713394
Sample ID for MGYA00085668: ERR1713370
Sample ID for MGYA00085669: ERR1726009
Sample ID for MGYA00085670: ERR1713397
Sample ID for MGYA00085671: ERR1726011
Sample ID for MGYA00085672: ERR1725969
Sample ID for MGYA00085673: ERR1713352
Sample ID for MGYA00085674: ERR1726015
Sample ID for MGYA00085675: ERR1726007
Sample ID for MGYA00085676: ERR1725952
Sample ID for MGYA00085677: ERR1713350
Sample ID for MGYA00085678: ERR1725961
Sample ID for MGYA00085679: ERR1713354
Sample ID for MGYA00085680: ERR1713385
Sample ID for MGYA00085681: ERR1713403
Sample ID for MGYA00085682: ERR1713332
Sample ID for MGYA00085683: ERR1725967
Sample ID for MGYA00085684: ERR1725985
Sample ID for MGYA00085685: ERR1725973
Sample ID for MGYA00085686: ERR1725940
Sample ID for MGYA00085687: ERR1725964
Sample ID for MGYA00085688: ERR1725957
Sample ID for MGYA00085689: ERR1713369
Sample ID for MGYA00085690: ERR1713366
Sample ID for MGYA00085691: ERR1725939
Sample ID for MGYA00085692: ERR1725942
Sample ID for MGYA00085693: ERR1725995
Sample ID for MGYA00085694: ERR1725958
Sample ID for MGYA00085695: ERR1713344
Sample ID for MGYA00085696: ERR1713353
Sample ID for MGYA00085697: ERR1713364
Sample ID for MGYA00085698: ERR1713405
Sample ID for MGYA00085699: ERR1725959
Sample ID for MGYA00085700: ERR1725988
Sample ID for MGYA00085701: ERR1725979
Sample ID for MGYA00085702: ERR1713388
Sample ID for MGYA00085703: ERR1725982
Sample ID for MGYA00085704: ERR1726031
Sample ID for MGYA00085705: ERR1725949
Sample ID for MGYA00085706: ERR1713402
Sample ID for MGYA00085707: ERR1726004
Sample ID for MGYA00085708: ERR1725962
Sample ID for MGYA00085709: ERR1726012
Sample ID for MGYA00085710: ERR1713371
Sample ID for MGYA00085711: ERR1713378
Sample ID for MGYA00085712: ERR1713347
Sample ID for MGYA00085713: ERR1713355
Sample ID for MGYA00085714: ERR1726000
Sample ID for MGYA00085715: ERR1725956
Sample ID for MGYA00085716: ERR1713345
Sample ID for MGYA00085717: ERR1725953
Sample ID for MGYA00085718: ERR1725954
Sample ID for MGYA00085719: ERR1713372
Sample ID for MGYA00085720: ERR1713410
Sample ID for MGYA00085721: ERR1726003
Sample ID for MGYA00085722: ERR1726033
Sample ID for MGYA00085723: ERR1726002
Sample ID for MGYA00085724: ERR1725945
Sample ID for MGYA00085725: ERR1713358
Sample ID for MGYA00085726: ERR1726030
Sample ID for MGYA00085727: ERR1725947
Sample ID for MGYA00085728: ERR1725976
Sample ID for MGYA00085729: ERR1725972
Sample ID for MGYA00085730: ERR1713383
Sample ID for MGYA00085731: ERR1713400
Sample ID for MGYA00085732: ERR1726028
Sample ID for MGYA00085733: ERR1713381
Sample ID for MGYA00085734: ERR1713382
Sample ID for MGYA00085735: ERR1713335
Sample ID for MGYA00085736: ERR1726021
Sample ID for MGYA00085737: ERR1713401
Sample ID for MGYA00085738: ERR1726027
Sample ID for MGYA00085739: ERR1713395
Sample ID for MGYA00085740: ERR1713367
Sample ID for MGYA00085741: ERR1725948
Sample ID for MGYA00085742: ERR1725951
Sample ID for MGYA00085743: ERR1725996
Sample ID for MGYA00085744: ERR1713390
Sample ID for MGYA00085745: ERR1713368
Sample ID for MGYA00085746: ERR1726022
Sample ID for MGYA00085747: ERR1726024
Sample ID for MGYA00085748: ERR1725990
Sample ID for MGYA00085749: ERR1713340
Sample ID for MGYA00085750: ERR1713387
Sample ID for MGYA00085751: ERR1713362
Sample ID for MGYA00085752: ERR1726023
Sample ID for MGYA00085753: ERR1725997
Sample ID for MGYA00085754: ERR1726008
Sample ID for MGYA00085755: ERR1726014
Sample ID for MGYA00085756: ERR1725984
Sample ID for MGYA00085757: ERR1725971
Sample ID for MGYA00085758: ERR1725975
Sample ID for MGYA00085759: ERR1725983
Sample ID for MGYA00085760: ERR1713379
Sample ID for MGYA00085761: ERR1725981
Sample ID for MGYA00085762: ERR1713409
Sample ID for MGYA00085763: ERR1713393
Sample ID for MGYA00085764: ERR1713373
Sample ID for MGYA00085765: ERR1713356
Sample ID for MGYA00085766: ERR1726035
Sample ID for MGYA00085767: ERR1725993
Sample ID for MGYA00085768: ERR1713396
Sample ID for MGYA00085769: ERR1726032
Sample ID for MGYA00085770: ERR1726016
Sample ID for MGYA00085771: ERR1726029
Sample ID for MGYA00085772: ERR1725968
Sample ID for MGYA00085773: ERR1726006
Sample ID for MGYA00085774: ERR1713334
Sample ID for MGYA00085775: ERR1713408
Sample ID for MGYA00085776: ERR1725943
Sample ID for MGYA00085777: ERR1713380
Sample ID for MGYA00085778: ERR1726010
Sample ID for MGYA00085779: ERR1726013
Sample ID for MGYA00085780: ERR1725974
Sample ID for MGYA00085781: ERR1713377
Sample ID for MGYA00085782: ERR1726018
Sample ID for MGYA00085783: ERR1725960
Sample ID for MGYA00085784: ERR1713374
Sample ID for MGYA00085785: ERR1713359
Sample ID for MGYA00085786: ERR1726019
Sample ID for MGYA00085787: ERR1713363
Sample ID for MGYA00085788: ERR1725978
Sample ID for MGYA00085789: ERR1713361
Sample ID for MGYA00085790: ERR1713365
Sample ID for MGYA00085791: ERR1726001
Sample ID for MGYA00085792: ERR1713375
Sample ID for MGYA00085793: ERR1726025
Sample ID for MGYA00085794: ERR1725980
Sample ID for MGYA00085795: ERR1725963
Sample ID for MGYA00085796: ERR1713384
Sample ID for MGYA00085797: ERR1725965
Sample ID for MGYA00085798: ERR1725966
Sample ID for MGYA00085799: ERR1725950
Sample ID for MGYA00085800: ERR1726034

        accession   sample_id
0    MGYA00216443  ERR1713390
1    MGYA00216444  ERR1713337
2    MGYA00216445  ERR1726005
3    MGYA00216446  ERR1725950
4    MGYA00216447  ERR1725956
..            ...         ...
408  MGYA00085796  ERR1713384
409  MGYA00085797  ERR1725965
410  MGYA00085798  ERR1725966
411  MGYA00085799  ERR1725950
412  MGYA00085800  ERR1726034

[413 rows x 2 columns]

In [99]:
metadata = pd.read_csv("SraRunTable-4.csv", usecols=["Run", "geographic_location_(country_and/or_sea)"])

metadata = metadata.rename(columns={"Run": "sample_id", "geographic_location_(country_and/or_sea)": "location"})

merged_data = pd.merge(df_samples, metadata, on=["sample_id"], how="left")

final_pd = pd.merge(merged_data, concat_pd, on=["accession"], how="inner")

final_pd.to_csv("../count/DTU-GE_phylum_count_data.csv", index=False)

In [112]:
country_counts = final_pd["location"].value_counts()
keep = country_counts[country_counts >= 15].index
df_filtered = final_pd[final_pd["location"].isin(keep)]
df_filtered["location"].nunique()

4